### ISSUE TITLE
Any BTC transaction signing examples?

### ISSUE THREAD

**Issue by bitcoinbrisbane** [MelbourneDeveloper/KeepKey.Net#6]
Is there any documentation or examples on how to use the MessageType_SimpleSignTx message?

**Comment by MelbourneDeveloper** [comment]
@bitcoinbrisbane good question! 

Firstly, KeepKey basically has the same protocol/messaging system as Trezor. The KeepKey.Net library is based on Trezor. So, however Trezor works for signing transactions should be more or less the same, or very similar to KeepKey. So, it's best to watch the Trezor.Net repo because that will be the first place I put a bitcoin transaction sample. https://github.com/MelbourneDeveloper/Trezor.Net

The first thing is that signing a Bitcoin transaction on Trezor/KeepKey does not seem to be simple. At first, I thought the message would be SimpleSignTx, or SignTx, but these messages don't have enough information on them to create a transaction. So, after some digging, I think I've realized that actually, it should be a TxAck message. I have had a stab at this in Trezor like so:

```
        public async Task SignTx()
        {
            var from = AddressPathBase.Parse<BIP44AddressPath>("m/49'/0'/0'/0/0");

            await GetAndInitialize();
            var txRequest = await TrezorManager.SendMessageAsync<object, TxAck>
                (new TxAck
                {                    
                    Tx = new TxAck.TransactionType
                    {
                        Inputs =
                        {
                            new TxAck.TransactionType.TxInputType
                            {
                                 AddressNs =from.ToArray(),
                                 Amount = 1,
                                  ScriptType= InputScriptType.Spendaddress
                            }
                        },
                        Outputs =
                        {
                            new TxAck.TransactionType.TxOutputType
                            {
                                 Address="3PvvQuKGyGSsvu8zuqRMEsSWnHrJZfatJv",
                                 AddressNs=from.ToArray(),
                                            ScriptType=  TxAck.TransactionType.TxOutputType.OutputScriptType.Paytoaddress
                  }
                        }
                    }
                });
        }
```

This fails with the message "missing required field". I'm not sure what would happen if I used the same code for KeepKey. But, anyway, my process to figure out how it should work will be to use the Trezor python, or Trezor Go libraries to reverse engineer the code. Unfortunately, I don't think any KeepKey libraries are open source, so I don't know of any hints on how to do it. But, here is the line from the Trezor python library for signing BTC transactions:

https://github.com/trezor/python-trezor/blob/b0a227866ad4fe4320720422d81ae8caa2999c9f/trezorlib/btc.py#L90

Please have a look at this. It might give you some hints on how to proceed. I will sit down and work through this at some point, but I doubt it will be in the near future.

**Comment by ep0x** [comment]
Hi, first of all i wish to thanks for awesome job!  Second i will explain how i managed to sign TX!

Signing a transaction is a little bit complicated. The reason is that transactions can be several hundred kilobytes in size, but TREZOR has only 64 kilobytes memory. So it is the task of the computer to split the transactions in small pieces and send only those pieces that TREZOR requested. The general workflow is given below : 
![signtx_workflow](https://user-images.githubusercontent.com/45769848/50017281-e9c13f00-ffcb-11e8-9795-da212f432ce5.png)

As we can see on diagram, we need to send a SignTx message first to the Trezor so he will open communication with us and send us back TxRequest. TxRequest form Trezor can vary  for example he ask us for TxRequest Type of Tx_Input, Tx_Output or ButtonRequest etc. So we need to make sure to send  correct type of the Request. All Reqeust for transaction we want to sign shall be sent in TxAck type.

I commented code for better understanding:


        public async Task SignBitcoinTransactionTask()
        {
            // initialize connection with device
            await GetAndInitialize();

            //get address path for address in Trezor
            var addressPath = AddressPathBase.Parse<BIP44AddressPath>("m/49'/0'/0'/0/0").ToArray();

            // previous unspent input of Transaction
            var txInput = new TxAck.TransactionType.TxInputType()
            {
                AddressNs  = addressPath,
                Amount     = 100837,
                ScriptType = InputScriptType.Spendp2shwitness,
                PrevHash   = "c28afd728ae0d6783034ea815af2c80e47d7695c719365cfe5d8fcb390c52931".ToHexBytes(), // transaction ID
                PrevIndex  = 0,
                Sequence   = 4294967293 // Sequence  number represent Replace By Fee 4294967293 or leave empty for default 
            };

            // TX we want to make a payment
            var txOut = new TxAck.TransactionType.TxOutputType()
            {
                AddressNs = new uint[0], Amount = 100837, Address = "35hK24tcLEWcgNA4JxpvbkNkoAcDGqQPsP", ScriptType = TxAck.TransactionType.TxOutputType.OutputScriptType.Paytoaddress // if is segwit use Spendp2shwitness

            };

            // Must be filled with basic data like below
            var signTx = new SignTx()
            {
                Expiry       = 0,
                LockTime     = 0,
                CoinName     = "Bitcoin",
                Version      = 2,
                OutputsCount = 1,
                InputsCount  = 1
            };

            // For every TX request from Trezor to us, we response with TxAck like below
            var txAck = new TxAck()
            {
                Tx = new TxAck.TransactionType()
                {
                    Inputs     = {txInput}, // Tx Inputs
                    Outputs    = {txOut},   // Tx Outputs
                    Expiry     = 0,
                    InputsCnt  = 1, // must be exact number of Inputs count
                    OutputsCnt = 1, // must be exact number of Outputs count
                    Version    = 2
                }
            };

            // If the field serialized.serialized_tx from Trezor is set,
            // it contains a chunk of the signed transaction in serialized format.
            // The chunks are returned in the right order and just concatenating all returned chunks will result in the signed transaction.
            // So we need to add chunks to the list
            var serializedTx = new List<byte>();

            // We send SignTx() to the Trezor and we wait him to send us Request
            var request = await TrezorManager.SendMessageAsync<TxRequest, object>(signTx);

            // We do loop here since we need to send over and over the same transactions to trezor because his 64 kilobytes memory
            // and he will sign chunks and return part of signed chunk in serialized manner, until we receive finall type of Txrequest TxFinished
            while (request.request_type != TxRequest.RequestType.Txfinished)
            {
                switch (request.request_type)
                {
                    case TxRequest.RequestType.Txinput:
                    {
                        //We send TxAck() with  TxInputs
                        request = await TrezorManager.SendMessageAsync<TxRequest, object>(txAck);

                        // Now we have to check every response is there any SerializedTx chunk 
                        if (request.Serialized != null)
                        {
                            // if there is any we add to our list bytes
                            serializedTx.AddRange(request.Serialized.SerializedTx);
                        }

                        break;
                    }
                    case TxRequest.RequestType.Txoutput:
                    {
                        //We send TxAck()  with  TxOutputs
                        request = await TrezorManager.SendMessageAsync<TxRequest, object>(txAck);

                        // Now we have to check every response is there any SerializedTx chunk 
                        if (request.Serialized != null)
                        {
                            // if there is any we add to our list bytes
                            serializedTx.AddRange(request.Serialized.SerializedTx);
                        }

                        break;
                    }

                    case TxRequest.RequestType.Txextradata:
                    {
                        // for now he didn't ask me for extra data :)
                        break;
                    }
                    case TxRequest.RequestType.Txmeta:
                    {
                        // for now he didn't ask me for extra Tx meta data :)
                        break;
                    }

                }


            }

            Debug.WriteLine($"TxSignature: {serializedTx.ToArray().ToHexCompact()}");

          
        }


DONE! :)

I spent to much time for this work but we did it! :)

**Comment by bitcoinbrisbane** [comment]
Wowers!  Both of you rock!  Also, I was hopping there was a "Sign Raw" so we could build the tx in NBitcoin. @ljupko123 got a btc tip jar?  Happy to throw you a few satoshis for your time.

**Comment by MelbourneDeveloper** [comment]
@bitcoinbrisbane the donation addresses are here: https://github.com/MelbourneDeveloper/KeepKey.Net#donate but in this particular case, the thanks go to @ljupko123

**Comment by MelbourneDeveloper** [comment]
@ljupko123 it would be great if you could submit a pull request for this.

I will also build this code in to TrezorManagerBase so that it is more straight forward to call and test this on the Trezor.

**Comment by MelbourneDeveloper** [comment]
@ljupko123 this code works perfectly on Trezor, and only required tiny modifications on KeepKey. If you're interested, you can look at this issue: https://github.com/MelbourneDeveloper/Hardwarewallets.Net/issues/1. It's Ethereum specific, but there is an overall question of how transaction signing should be done across coins... When this is bedded down, a method called SignTransaction<> will be rolled out across all three hardwarewallet libraries.

**Comment by MelbourneDeveloper** [comment]
@bitcoinbrisbane I have added the sample to the KeepKey unit tests. You can see it here:
https://github.com/MelbourneDeveloper/KeepKey.Net/blob/eb475e7c1ab67887e656f788a0b3b6e745f41a95/src/KeepKey.Net.UnitTest/UnitTest.cs#L221

Is it OK to close this issue now?

**Comment by ljupko123** [comment]
Sure mate!  Sorry for late response since our time zone are different my
clock now is 11:38 AM. To be honest i didn't use Github before, usually
using BitBucket.
I will look this
https://github.com/MelbourneDeveloper/Hardwarewallets.Net/issues/1 and sure
i will try to help :)
I did try to create pull request as you requested in comment but i don't
know how :)

Do you work for some company there in Australia?
Best regards

**Comment by ep0x** [comment]
Sure you can close and do not forget to add that "0" in beginning of signed transaction in unit test.
I  will look at this https://github.com/MelbourneDeveloper/Hardwarewallets.Net/issues/1 and i will try to help.

**Comment by ep0x** [comment]
> Wowers! Both of you rock! Also, I was hopping there was a "Sign Raw" so we could build the tx in NBitcoin. @ljupko123 got a btc tip jar? Happy to throw you a few satoshis for your time.

I will try to create method for Sign Raw transactions and @MelbourneDeveloper can include in his awesome lib.


Please donate here https://github.com/MelbourneDeveloper/KeepKey.Net#donate
His work deserve much more!

**Comment by MelbourneDeveloper** [comment]
@bitcoinbrisbane can this issue be closed now, or are you still having trouble?

**Comment by bitcoinbrisbane** [comment]
> @bitcoinbrisbane can this issue be closed now, or are you still having trouble?

Im good!  Thanks everyone for the help.  Please close and have a great new year!
